In the lecture, we talked about RBF networks and LSTM networks. We will use the RBF networks to show how we can implement custom layer in tesorflow

# RBF Networks

Implementing a custom layer in tensorflow is simple. We just have to implement a class with a `build` method that inicializes the parameters according to the size of the input, and a `call` method that implements the computation of the layer itself.

In [1]:
import tensorflow as tf

class RBFLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs, init):
        super(RBFLayer, self).__init__()
        self.num_outputs = num_outputs
        self.init = init
    
    def build(self, input_shape):
        self.centers = self.add_weight(name="centers", shape=(self.num_outputs, int(input_shape[-1])), initializer=self.init)
        self.beta = self.add_weight(name="beta", shape=(self.num_outputs,))
    
    def compute_output_shape(self, input_shape):
        return input_shape[0], self.num_outputs
    
    def call(self, x):
        C = tf.expand_dims(self.centers, -1)
        #print(C.shape)
        #print(tf.transpose(x).shape)
        
        H = tf.transpose(C - tf.transpose(x))
        #print(H.shape)
        #print(tf.reduce_sum(tf.pow(H, 2), axis=1).shape)
        
        return tf.math.exp(-self.beta * tf.reduce_sum(tf.pow(H,2), axis=1))                               

2024-04-15 14:47:56.080320: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-15 14:47:56.238454: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-04-15 14:47:56.238516: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [6]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
x, y = iris.data, iris.target

from sklearn import cluster

clf = cluster.KMeans(n_clusters=10)
clf.fit(x, y)
print(clf.cluster_centers_)

model = tf.keras.Sequential([
    RBFLayer(12, init=tf.constant_initializer(clf.cluster_centers_)),
    tf.keras.layers.Dense(3, activation=tf.nn.softmax)
]
)

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc'])

model.fit(x, y, epochs=1000, verbose=False)
np.mean(np.argmax(model.predict(x), axis=1)==y)

[[6.03684211 2.70526316 5.         1.77894737]
 [5.1125     3.52083333 1.525      0.27083333]
 [5.66153846 2.56153846 3.87692308 1.16923077]
 [7.54       3.15       6.39       2.09      ]
 [6.61666667 3.07916667 5.5625     2.1375    ]
 [4.67894737 3.08421053 1.37894737 0.2       ]
 [6.49411765 2.95882353 4.60588235 1.41764706]
 [5.         2.3        3.275      1.025     ]
 [5.52857143 4.04285714 1.47142857 0.28571429]
 [5.63846154 2.89230769 4.33846154 1.4       ]]


TypeError: in user code:

    File "/home/gabi/.env/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/home/gabi/.env/lib/python3.8/site-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/gabi/.env/lib/python3.8/site-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/home/gabi/.env/lib/python3.8/site-packages/keras/engine/training.py", line 889, in train_step
        y_pred = self(x, training=True)
    File "/home/gabi/.env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/ipykernel_3929/3524676246.py", line 10, in build
        self.centers = self.add_weight("centers", shape=(self.num_outputs, int(input_shape[-1])), initializer=self.init)

    TypeError: Exception encountered when calling layer "sequential_2" (type Sequential).
    
    Eager execution of tf.constant with unsupported shape. Tensor [[6.036842   2.7052631  5.         1.7789474 ]
     [5.1125     3.5208333  1.525      0.27083334]
     [5.6615386  2.5615385  3.876923   1.1692308 ]
     [7.54       3.15       6.39       2.09      ]
     [6.616667   3.0791667  5.5625     2.1375    ]
     [4.6789474  3.0842106  1.3789474  0.2       ]
     [6.4941177  2.9588234  4.605882   1.417647  ]
     [5.         2.3        3.275      1.025     ]
     [5.5285716  4.042857   1.4714285  0.2857143 ]
     [5.6384616  2.8923078  4.3384614  1.4       ]] (converted from [[6.03684211 2.70526316 5.         1.77894737]
     [5.1125     3.52083333 1.525      0.27083333]
     [5.66153846 2.56153846 3.87692308 1.16923077]
     [7.54       3.15       6.39       2.09      ]
     [6.61666667 3.07916667 5.5625     2.1375    ]
     [4.67894737 3.08421053 1.37894737 0.2       ]
     [6.49411765 2.95882353 4.60588235 1.41764706]
     [5.         2.3        3.275      1.025     ]
     [5.52857143 4.04285714 1.47142857 0.28571429]
     [5.63846154 2.89230769 4.33846154 1.4       ]]) has 40 elements, but got `shape` (12, 4) with 48 elements).
    
    Call arguments received by layer "sequential_2" (type Sequential):
      • inputs=tf.Tensor(shape=(None, 4), dtype=float32)
      • training=True
      • mask=None


## Exercise

We can see that our implementation does not work very well. In the lecture, we mentioned that the centers of the input neurons are commonly initialized using the $k$-means algoriths. Try to change our implementation so that it uses this method. (Hint: the `add_weights` method has an `initializer` argument.)

# LSTM networks

LSTM networks are used to process texts and time-series data. We will show how they can be used to generate text. We will use Nietzsches texts as a training set

In [3]:
import numpy as np
import random
import sys

'''
    Example script to generate text from Nietzsche's writings.
    At least 20 epochs are required before the generated text
    starts sounding coherent.
    It is recommended to run this script on GPU, as recurrent
    networks are quite computationally intensive.
    If you try this script on new data, make sure your corpus
    has at least ~100k characters. ~1M is better.
'''

path = tf.keras.utils.get_file('nietzsche.txt', origin="https://s3.amazonaws.com/text-datasets/nietzsche.txt")
text = open(path).read().lower()
print('corpus length:', len(text))

chars = set(text)
print('total chars:', len(chars))
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

# cut the text in semi-redundant sequences of maxlen characters
maxlen = 20
step = 3
sentences = []
next_chars = []
for i in range(0, len(text) - maxlen, step):
    sentences.append(text[i: i + maxlen])
    next_chars.append(text[i + maxlen])
print('nb sequences:', len(sentences))

print('Vectorization...')
X = np.zeros((len(sentences), maxlen, len(chars)), dtype=np.bool_)
y = np.zeros((len(sentences), len(chars)), dtype=np.bool_)
for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        X[i, t, char_indices[char]] = 1
    y[i, char_indices[next_chars[i]]] = 1
    
print('Build model...')
model = tf.keras.Sequential()
model.add(tf.keras.layers.LSTM(512, return_sequences=True, input_shape=(maxlen, len(chars))))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.LSTM(512, return_sequences=False))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(len(chars), activation=tf.nn.softmax))

model.compile(loss='categorical_crossentropy', optimizer='rmsprop')


def sample(a, temperature=1.0):
    # helper function to sample an index from a probability array
    a = np.log(a) / temperature
    a = np.exp(a) / np.sum(np.exp(a))
    a = a/np.sum(a)
    return np.argmax(np.random.multinomial(1, a, 1))

# train the model, output generated text after each iteration
for iteration in range(1, 60):
    print()
    print('-' * 50)
    print('Iteration', iteration)
    model.fit(X, y, batch_size=128, epochs=1)

    start_index = random.randint(0, len(text) - maxlen - 1)

    for diversity in [0.2, 0.5, 1.0, 1.2]:
        print()
        print('----- diversity:', diversity)

        generated = ''
        sentence = text[start_index: start_index + maxlen]
        generated += sentence
        print('----- Generating with seed: "' + sentence + '"')
        sys.stdout.write(generated)

        for _ in range(400):
            x = np.zeros((1, maxlen, len(chars)))
            for t, char in enumerate(sentence):
                x[0, t, char_indices[char]] = 1.

            preds = model.predict(x, verbose=0)[0]
            next_index = sample(preds, diversity)
            next_char = indices_char[next_index]

            generated += next_char
            sentence = sentence[1:] + next_char

            sys.stdout.write(next_char)
            sys.stdout.flush()
        print()


corpus length: 600893
total chars: 57
nb sequences: 200291
Vectorization...
Build model...

--------------------------------------------------
Iteration 1
 831/1565 [==============>...............] - ETA: 4:08 - loss: 2.4734

KeyboardInterrupt: 

Running this cell on a PC without GPU would take several hours. Therefore I ran it in the Google Colab platform and you can [check the results](https://colab.research.google.com/drive/1B7zys275xmpPqahPwNvuYMPLmgvlV3l5).

## PyTorch version

For the model definition, torch is simpler (no build(), no weird initializer). However, it is more sensitive to shapes - tensorflow automatically matches dimensions in self.centers - tf.transpose(x) or self.beta * tf.reduce_sum(...), while here we have to call unsqueeze() (like np.newaxis). Try to remove .unsqueeze() from forward and look at the errors :-)

The training code is again longer, and more sensitive to types.

In [7]:
import torch
from torch import nn
from torch.utils.data import TensorDataset, DataLoader
from torch import optim
import torch.nn.functional as F


class RBFModule(nn.Module):
    def __init__(self, input_shape, num_outputs, init=None):
        super().__init__()
        self.num_outputs = num_outputs
        self.init = init
        
        self.centers = torch.rand(self.num_outputs, int(input_shape)) if init is None else torch.tensor(init).float()
        self.beta = torch.rand((self.num_outputs,))
        
        self.centers = torch.unsqueeze(self.centers, -1)
    
    def forward(self, x):
        H = torch.permute(self.centers - torch.permute(x, (1, 0)).unsqueeze(0), (2, 1, 0))
        
        return torch.exp(-self.beta * torch.sum(torch.pow(H, 2), axis=1))                     

In [9]:
mod = nn.Sequential(
    RBFModule(4, 10, init=clf.cluster_centers_),
    nn.Linear(10, 3)
)

mod(torch.tensor(x).float()).shape

# create DataLoader for batching
x_tensor, y_tensor = torch.tensor(x).float(), torch.tensor(y).long()
train_data = TensorDataset(x_tensor, y_tensor)
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)

# fit and predict
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(mod.parameters())

# train the network
for epoch in range(1000):
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        output = mod(inputs)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()

# predict
preds = []
with torch.no_grad():
    predictions = mod(torch.tensor(x).float())
    predictions = F.softmax(predictions, dim=1).numpy()
    print(np.mean(np.argmax(predictions, axis=1) == y))

[[9.96868551e-01 1.94394658e-03 1.18752231e-03]
 [9.93437827e-01 4.04059747e-03 2.52160127e-03]
 [9.94407773e-01 3.33167776e-03 2.26065330e-03]
 [9.92521465e-01 4.55915416e-03 2.91932141e-03]
 [9.96883035e-01 1.91803055e-03 1.19899213e-03]
 [9.95631933e-01 2.78145215e-03 1.58662628e-03]
 [9.94426489e-01 3.34918872e-03 2.22439831e-03]
 [9.96294200e-01 2.33088736e-03 1.37481035e-03]
 [9.87905622e-01 7.04367831e-03 5.05075371e-03]
 [9.94089127e-01 3.67851555e-03 2.23240955e-03]
 [9.96823907e-01 1.99173973e-03 1.18443114e-03]
 [9.95236099e-01 2.99757393e-03 1.76636060e-03]
 [9.93033528e-01 4.21751756e-03 2.74895784e-03]
 [9.86355245e-01 7.49916909e-03 6.14555459e-03]
 [9.93384659e-01 3.85543611e-03 2.75992393e-03]
 [9.90258217e-01 5.62226446e-03 4.11956664e-03]
 [9.96575892e-01 2.08151084e-03 1.34256273e-03]
 [9.96825695e-01 1.98167027e-03 1.19272713e-03]
 [9.94024813e-01 3.78303300e-03 2.19215616e-03]
 [9.96910512e-01 1.92307727e-03 1.16645871e-03]
 [9.94706929e-01 3.48201627e-03 1.811067

## LSTM

Apart from the training code being longer, note how there is no softmax in the last output layer. This is because CrossEntropyLoss computes it *inside*. This is why we have to call softmax manually in the sample function to get actual probabilities and not logits.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import random
import sys
import requests

from tqdm import tqdm

'''
    Example script to generate text from Nietzsche's writings.
    At least 20 epochs are required before the generated text
    starts sounding coherent.
    It is recommended to run this script on GPU, as recurrent
    networks are quite computationally intensive.
    If you try this script on new data, make sure your corpus
    has at least ~100k characters. ~1M is better.
'''

def download_nietzsche_text():
    url = "https://s3.amazonaws.com/text-datasets/nietzsche.txt"
    response = requests.get(url)
    text = response.text.lower()
    return text

text = download_nietzsche_text()
print('corpus length:', len(text))

chars = sorted(set(text))
print('total chars:', len(chars))
char_indices = {char: i for i, char in enumerate(chars)}
indices_char = {i: char for i, char in enumerate(chars)}

# cut the text in semi-redundant sequences of maxlen characters
maxlen = 20
step = 3
sentences = []
next_chars = []
for i in range(0, len(text) - maxlen, step):
    sentences.append(text[i: i + maxlen])
    next_chars.append(text[i + maxlen])
print('nb sequences:', len(sentences))

print('Vectorization...')
X = np.zeros((len(sentences), maxlen, len(chars)), dtype=np.float32)
y = np.zeros((len(sentences), len(chars)), dtype=np.float32)
for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        X[i, t, char_indices[char]] = 1
    y[i, char_indices[next_chars[i]]] = 1

class CharRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(CharRNN, self).__init__()
        self.hidden_size = hidden_size
        self.lstm1 = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.dropout = nn.Dropout(0.2)
        self.lstm2 = nn.LSTM(hidden_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.lstm1(x)
        out = self.dropout(out)
        out, _ = self.lstm2(out)
        out = self.dropout(out)
        out = self.fc(out[:, -1, :])
        return out

device = 'cuda'

input_size = len(chars)
hidden_size = 512
output_size = len(chars)
model = CharRNN(input_size, hidden_size, output_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.RMSprop(model.parameters(), lr=0.001)

def sample(logits, temperature=1.0):
    # helper function to sample an index from a probability array
    logits = logits / temperature
    prob = torch.softmax(logits, dim=-1)
    return torch.multinomial(prob, 1).item()

# Training parameters
batch_size = 128
num_epochs = 60

# train the model, output generated text after each iteration
for epoch in range(num_epochs):
    print()
    print('-' * 50)
    print('Epoch', epoch+1)

    # Shuffle data
    indices = np.arange(len(X))
    np.random.shuffle(indices)
    X = X[indices]
    y = y[indices]

    pbar = tqdm(range(0, len(X), batch_size))
    for i in pbar:
        optimizer.zero_grad()
        batch_X = torch.tensor(X[i:i+batch_size], dtype=torch.float32)
        batch_y = torch.tensor(np.argmax(y[i:i+batch_size], axis=1), dtype=torch.long)

        output = model(batch_X.to(device))
        loss = criterion(output, batch_y.to(device))
        loss.backward()
        optimizer.step()
        
        pbar.set_postfix({'loss': loss.item()})

    start_index = random.randint(0, len(text) - maxlen - 1)

    for diversity in [0.2, 0.5, 1.0, 1.2]:
        print()
        print('----- diversity:', diversity)

        generated = ''
        sentence = text[start_index: start_index + maxlen]
        generated += sentence
        print('----- Generating with seed: "' + sentence + '"')
        sys.stdout.write(generated)

        for _ in range(400):
            x = torch.zeros(1, maxlen, len(chars), dtype=torch.float32)
            for t, char in enumerate(sentence):
                x[0, t, char_indices[char]] = 1.

            with torch.no_grad():
                logits = model(x.to(device))
            next_index = sample(logits.detach().cpu()[0], diversity)
            next_char = indices_char[next_index]

            generated += next_char
            sentence = sentence[1:] + next_char

            sys.stdout.write(next_char)
            sys.stdout.flush()
        print()
